AWSTemplateFormatVersion: '2010-09-09'
Description: Simple AWS X-Ray sample template

Resources:

  XRayDaemonRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: xray-daemon-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess

  XRayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/xray/sample
      RetentionInDays: 14

Outputs:
  XRayDaemonRoleArn:
    Value: !GetAtt XRayDaemonRole.Arn
